resolver: lts-5.12
packages:
  - '.'
  - location:
      git: https://github.com/agrafix/ghcjs-ajax
      commit: 03007d96ec266bce343879c533713eaadfe5f7ae
    subdirs:
      - ghcjs-ajax
    extra-dep: true


extra-deps:
  - react-flux-1.0.7

compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
        sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3
